server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redireciona /api/* para o backend (sem CORS em produção)
    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Garante que as rotas do Angular funcionem (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
