# Substituir SEU_USUARIO pelo seu username do SonarCloud/GitHub
sonar.projectKey=matheusvhs_matheusvhs-spring
sonar.organization=matheusvhs
sonar.projectName=matheusvhs-spring

sonar.language=java
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/BackendApplication.java
