spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: never

portfolio:
  admin:
    username: ${PORTFOLIO_ADMIN_USERNAME}
    password: ${PORTFOLIO_ADMIN_PASSWORD}
  cors:
    allowed-origin: ${PORTFOLIO_CORS_ORIGIN}
